# Generated by Django 3.2 on 2022-06-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
