# Generated by Django 4.0.4 on 2022-07-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'Rasm kategoriyalari',
            },
        ),
        migrations.RenameField(
            model_name='carusel',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='carusel',
            name='image',
            field=models.ImageField(upload_to='carusel/', verbose_name='Rasm'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='nomi')),
                ('image', models.ImageField(upload_to='images/', verbose_name='rasm')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra.imgcategory')),
            ],
            options={
                'verbose_name': 'rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ('id',),
            },
        ),
    ]
